### ISSUE TITLE
can output tif keep layers ？

### ISSUE THREAD

**Issue by jindili** [cgohlke/psdtags#1]
some small tweak to the example on pypi page,
tif saved successful, but the layer were flattern.

Is is possible to keep the layers on ouput tif image ?

```python
from tifffile import imread, imwrite
import psdtags

isd = psdtags.TiffImageResources.fromtiff('input_2layer.tif')
res = psdtags.TiffImageResources.fromtiff('input_2layer.tif')

image = imread('input_2layer.tif')
imwrite(
    'output_layered_tiff.tif',
    image,
    byteorder=isd.psdformat.byteorder,  # must match ImageSourceData
    photometric='rgb',  # must match ImageSourceData
    metadata=None,  # do not write any tifffile specific metadata
    extratags=[isd.tifftag(), res.tifftag()],
)

```

**Comment by cgohlke** [comment]
Can you share the file? For the example I am using the layers stay layered, which is the purpose of the package. It is validated by `assert isd == TiffImageSourceData.fromtiff('_layered.tif')` in the docstring.

**Comment by jindili** [comment]
sure, here is the file
[input_2layer.zip](https://github.com/cgohlke/psdtags/files/8085191/input_2layer.zip)

![image](https://user-images.githubusercontent.com/73845/154395887-80ef69a8-65fa-497e-8385-e1012e6e03b0.png)

**Comment by cgohlke** [comment]
Try `isd = psdtags.TiffImageSourceData.fromtiff('test_issue1.tif')` instead of `isd = psdtags.TiffImageResources.fromtiff('test_issue1.tif')`

**Comment by jindili** [comment]
Great!, the layer is now keeped.

Is is possible to add new layer and import data from another image file ?
I start a new issue for that.
