### ISSUE TITLE
cannot find all the layers in TIFF

### ISSUE THREAD

**Issue by eroux** [cgohlke/psdtags#13]
Hello, and thanks for tackling the issue of PSD tags in TIFFs, this is really helpful!

This is a follow up of https://github.com/python-pillow/Pillow/issues/8323#issuecomment-2304160425 which I'll copy here:

I have the following tiff file:

[11b.zip](https://github.com/user-attachments/files/16708434/11b.zip)

That has two layers according to imagemagick:

```
$ identify 11b.tif 
11b.tif[0] TIFF 3926x852 3926x852+0+0 8-bit sRGB 18.6303MiB 0.030u 0:00.029
11b.tif[1] TIFF 3890x851 3890x851+36+1 8-bit sRGB 18.6303MiB 0.000u 0:00.000
identify-im6.q16: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/949.
```

but it seems psdtags only detects one:

```python
import psdtags
print(len(psdtags.TiffImageSourceData.fromtiff('11b.tif').layers))
```

prints `1`. Is there a way to get the number of layers in this tiff file through psdtags?

Thanks!

**Comment by cgohlke** [comment]
There is only one layer image in the `ImageSourceData` tag value of your file. The other, regular image is from the first TIFF page. It's not a layer. There's also a smaller thumbnail image in the `ImageResources` tag value.
