### ISSUE TITLE
Smart object

### ISSUE THREAD

**Issue by dadwjiodjwad** [cgohlke/psdtags#14]
Hi,

What I need is to just be able to switch inside smart object various images I give so that I can programmatically insert images inside the SO and they have applied the perspective, distort, warp, opacity properties of the SO and I can then export the full image.

Would this be possible?

**Comment by cgohlke** [comment]
There are no classes for handling smart object layer data. You'll need to parse/synthesize it yourself and use psdtags to read/write the bytes from/to the TIFF tag. 

https://github.com/cgohlke/psdtags/blob/5b7f7d9ede1d33852d852abbddadcd82a908d077/psdtags/psdtags.py#L3555-L3556
