### ISSUE TITLE
Is is possible to add new layer and import data from another image file ?

### ISSUE THREAD

**Issue by jindili** [cgohlke/psdtags#2]
Is is possible to add new layer and import data from another image file ?
or change the image data of existing layer?

**Comment by cgohlke** [comment]
You can change existing `PsdChannel.data` numpy arrays and any other attributes of the layers, add or delete `PsdLayer` instances to/from the `PsdLayers.layers` list, and write the whole `TiffImageSourceData` instance back to a TIFF. There's no higher level API or additional documentation so you'll need to follow the Adobe specs and the source code. See also:

https://github.com/cgohlke/psdtags/blob/5e15d5cb6ea894b437248a9ff08b3c222a5b5ed6/psdtags/psdtags.py#L110-L114

https://github.com/cgohlke/psdtags/blob/5e15d5cb6ea894b437248a9ff08b3c222a5b5ed6/psdtags/psdtags.py#L138-L145

https://github.com/cgohlke/psdtags/blob/5e15d5cb6ea894b437248a9ff08b3c222a5b5ed6/psdtags/psdtags.py#L39-L44

**Comment by jindili** [comment]
I try append layers from another tif, but get error on write

```python
from tifffile import imread, imwrite
import psdtags

isd = psdtags.TiffImageSourceData.fromtiff('input_2layer.tif')
res = psdtags.TiffImageResources.fromtiff('input_2layer.tif')

isd_layer3 = psdtags.TiffImageSourceData.fromtiff('layer3.tif')
res_layer3 = psdtags.TiffImageResources.fromtiff('layer3.tif')

isd.layers.layers = isd.layers.layers + isd_layer3.layers.layers

imwrite(
    'tmp_output.tif',
    isd,
    byteorder=isd.psdformat.byteorder,  # must match ImageSourceData
    photometric='rgb',  # must match ImageSourceData
    metadata=None,  # do not write any tifffile specific metadata
    extratags=[isd.tifftag(), res.tifftag()],
)

```

I try the second parameter of imwrite to 
isd or isd.tobytes()
both not work

attached files used in the python code
[test_psdtags.zip](https://github.com/cgohlke/psdtags/files/8086071/test_psdtags.zip)

**Comment by cgohlke** [comment]
Please follow the example:

https://github.com/cgohlke/psdtags/blob/5e15d5cb6ea894b437248a9ff08b3c222a5b5ed6/psdtags/psdtags.py#L134-L145

**Comment by jindili** [comment]
Yes, I follow the example on my first attempt to check multi layer tiff save, and that's successful.

But this time I add a new layer to the isd.layers.layers, and want to save the modified version.
