### ISSUE TITLE
How can I edit psd file

### ISSUE THREAD

**Issue by YiXinChenChen** [cgohlke/psdtags#6]
Thanks for providing this tool, one question is how to edit the psd file, for example, layer creation and replacement

**Comment by cgohlke** [comment]
Psdtags is a library to read and write the Adobe Photoshop specific tags in layered TIFF files. Adobe Photoshop PSD files have a different file format. Use the [psd-tools](https://github.com/psd-tools/psd-tools) library for working with PSD files.
